### ISSUE TITLE
Application service has not registered this user

### ISSUE THREAD

**Issue by chris-aeviator** [turt2live/matrix-appservice-webhooks#34] opened 2017-11-15 11:06 UTC
When following your instructions from `README.MD` and starting the server with `node index.js -p 9000 -c config/config.yaml` I get the following error output:

```
Nov-15-2017 11:57:05.964 +01:00 verbose [matrix-appservice-bridge] [-] GET http://localhost:8008/_matrix/client/r0/joined_rooms (AS) Body: 
Nov-15-2017 11:57:05.971 +01:00 info [WebService] API now listening on 0.0.0.0:4501
Nov-15-2017 11:57:05.995 +01:00 verbose [WebhookStore [SQL]] Executing (default): SELECT `id`, `objectId`, `key`, `value` FROM `account_data` AS `account_data` WHERE `account_data`.`objectId` = 'bridge';
Nov-15-2017 11:57:06.007 +01:00 verbose [matrix-appservice-bridge] [-] GET http://localhost:8008/_matrix/client/r0/joined_rooms (AS) HTTP 200 {"joined_rooms":[]}
Nov-15-2017 11:57:06.013 +01:00 verbose [utils] Downloading image from http://i.imgur.com/IDOBtEJ.png
Nov-15-2017 11:57:06.016 +01:00 verbose [matrix-appservice-bridge] [-] POST http://localhost:8008/_matrix/client/r0/register (AS) Body: {"auth":{},"username":"_webhook"}
Nov-15-2017 11:57:06.033 +01:00 error [matrix-appservice-bridge] [-] POST http://localhost:8008/_matrix/client/r0/register (AS) HTTP 400 Error: {"errcode":"M_USER_IN_USE","error":"User ID already taken."}
Nov-15-2017 11:57:06.036 +01:00 verbose [matrix-appservice-bridge] [-] GET http://localhost:8008/_matrix/client/r0/profile/%40_webhook%3Alocalhost/displayname (@_webhook:localhost) Body: 
Nov-15-2017 11:57:06.070 +01:00 verbose [matrix-appservice-bridge] [-] POST http://localhost:8008/_matrix/media/v1/upload (@_webhook:localhost) Body: {"type":"Buffer","data":[137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,3,132
Nov-15-2017 11:57:06.104 +01:00 error [matrix-appservice-bridge] [-] POST http://localhost:8008/_matrix/media/v1/upload (@_webhook:localhost) HTTP 403 Error: "{\"errcode\":\"M_FORBIDDEN\",\"error\":\"Application service has not registered this user\"}"
```

**Comment by chris-aeviator** [comment] 2017-11-15 11:12
realized that on the first run it created the user but errored out with `error [matrix-appservice-bridge] [-] GET http://localhost:8008/\\_matrix/client/r0/profile/%40\\_webhook%3Alocalhost/displayname (@\_webhook:localhost) HTTP 401 Error: {"errcode":"M_UNKNOWN","error":"Unauthorized"}`

I am still able to use the bot even if the main process crashes ?!

**Comment by turt2live** [comment] 2017-11-15 17:22
The first error, `{"errcode":"M_USER_IN_USE","error":"User ID already taken."}` is expected and not a problem.

The other error though is a bit more problematic. It sounds like the domain is not set to your homeserver's domain. 

https://github.com/turt2live/matrix-appservice-webhooks/blob/master/config/sample.yaml#L8
should be something like "matrix.org" or whatever your homeserver domain is.

**Comment by turt2live** [comment] 2018-06-08 19:12
Closing as this was presumably resolved. If the issue is still occurring, please open a new issue.

**Closed by turt2live** 2018-06-08 19:12 UTC
Labels: bug, question
