### ISSUE TITLE
Issue with notification from Gitlab 

### ISSUE THREAD

**Issue by szimszon** [turt2live/matrix-appservice-webhooks#38] opened 2018-05-31 07:23 UTC
Hi,

I was able to install the appservice for my HS successfully. But I have some problems with notification from GitLab (Slack notifications).
I receive the notification but there are no usable links inside but in the source of the message in Riot side I see some weird stuff...

I wonder if you could help me.

Here the string I captured with tcpdump:

`
payload=%7B%22username%22%3A%22Gitlab%22%2C%22attachments%22%3A%5B%5D%2C%22fallback%22%3Anull%2C%22text%22%3A%22Jakab+Gipsz+%28jgipsz%29+closed+%5Cu003chttps%3A%2F%2Fexample.com%2Fadmin%2Fgitlab%2FProject1%2Fansible%2Fmerge_requests%2F179%7C%21179+*Test+webhook*%5Cu003e+in+%5Cu003chttps%3A%2F%2Fexample.com%2Fadmin%2Fgitlab%2FProject1%2Fansible%7CProject1%2Fansible%5Cu003e%3A+*Test+webhook*%22%7D
`

After urldecode:

`
payload={
"username":"Gitlab",
"attachments":[],
"fallback":null,
"text":"Jakab Gipsz (jgipsz) closed \u003chttps://example.com/admin/gitlab/Project1/ansible/merge_requests/179|!179 *Test webhook*\u003e in \u003chttps://example.com/admin/gitlab/Project1/ansible|Project1/ansible\u003e: *Test webhook*"}
`

And the msg source from Riot:

`
{
  "origin_server_ts": 1527690275010,
  "sender": "@_webhook__MzjJH38dhjksWeeScb_example_com_Gitlab:example.com",
  "event_id": "$1525678268297yHRBu:example.com",
  "unsigned": {
    "age": 216
  },
  "content": {
    "body": "",
    "msgtype": "m.text",
    "formatted_body": "Jakab Gipsz (jgipsz) closed <https: example.com=\"\" admin=\"\" gitlab=\"\" project1=\"\" ansible=\"\" merge_requests=\"\" 179|!179=\"\" *test=\"\" webhook*=\"\"> in <https: example.com=\"\" admin=\"\" gitlab=\"\" project1=\"\" ansible|project1=\"\" ansible=\"\">: *Test webhook*</https:></https:>",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message",
  "room_id": "!MzjJH38dhjksWeeScb:example.com"
}
`

And all I can see in Riot client:

`Jakab Gipsz (jgipsz) closed in: *Test webhook*`

Without any useful links... :-o

**Comment by turt2live** [comment] 2018-05-31 17:11
Looks like we don't parse the slack link format correctly :(

In the meantime, something like https://t2bot.io/gitlab may work better for you (can be self-hosted).

**Comment by szimszon** [comment] 2018-06-01 12:35
Thank you for pointing this out. Unfortunately for us we have a different use case:
The bot receives events from gitlab and put it in a group chat room - ideally with usable links -, and after somebody had read the message he/she could just click the link and continue in the Gitlab webpage...

**Comment by szimszon** [comment] 2018-06-07 12:33
Hi!

I found a node library slackdown (https://github.com/blockmar/slackdown).
And I added it to src/processing/layers/message/html.js:

<code>
var slackdown = require('slackdown');

...

matrix.event.formatted_body = slackdown.parse(matrix.event.body);
</code>

Seems to work for me ;)

**Comment by turt2live** [comment] 2018-06-07 15:32
I remember taking a look at slackdown in the past, but there was something that went wrong so I ended up ditching it. I'll take another look though - it is possible that the issue I saw back then is fixed now.

**Comment by z3ntu** [comment] 2018-08-31 17:06
Duplicate of #14?

**Comment by turt2live** [comment] 2018-10-20 02:01
I think this should be fixed with #14

**Closed by turt2live** 2018-10-20 02:01 UTC
Labels: bug
